sonar.projectKey=Scord-Flutter
sonar.projectName=Scord Flutter
sonar.sources=lib
sonar.tests=test
sonar.language=dart
sonar.host.url=http://localhost:9000
sonar.login=sqp_d93c3b204aad26d28764f76121071897f8d018f2
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.gen.dart